server:
  port: 6161
spring:
  jackson:
    time-zone: Europe/Istanbul
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
    username: postgres
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@gmail.com
    password: ...
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

security:
  jwt:
    secret-key: "bXlWZXJ5TG9uZ1NlY3JldEtleVRoYXRJc0F0TGVhc3QzMkNoYXJhY3RlcnM="
    expiration-time: 3600000

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
